### PR TITLE
Fitting linear models using linear algebra for better performance

### PR DESCRIPTION
**Pull request by HeikoSchuett**
So far fitting the weighted model class relied on optimizing a function without derivatives, which is slow. This solves the problem for the cases where the linear algebra solutions work, i.e. OLS and ridge regression.

### CODE REVIEW

**Comment by ilogue** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pyrsa/model/fitter.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6354944&bid=20632947)

**Comment by ilogue** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- pyrsa/model/fitter.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6354944&bid=20632947)

**Comment by ilogue** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pyrsa/model/fitter.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6354944&bid=20632947)

**Comment by ilogue** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pyrsa/model/fitter.py  4
- pyrsa/util/pooling.py  16
         

Complexity decreasing per file
==============================
+ pyrsa/util/inference_util.py  -5
         

Clones added
============
- pyrsa/util/pooling.py  2
         

Clones removed
==============
+ pyrsa/util/inference_util.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6354944&bid=20632947)

**Comment by ilogue** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pyrsa/util/pooling.py  16
- pyrsa/model/fitter.py  4
         

Complexity decreasing per file
==============================
+ pyrsa/util/inference_util.py  -5
         

Clones added
============
- pyrsa/util/pooling.py  2
         

Clones removed
==============
+ pyrsa/util/inference_util.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6354944&bid=20632947)

**Comment by ilogue** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pyrsa/model/fitter.py  4
- pyrsa/util/pooling.py  16
         

Complexity decreasing per file
==============================
+ pyrsa/util/inference_util.py  -5
         

Clones added
============
- pyrsa/util/pooling.py  2
         

Clones removed
==============
+ pyrsa/util/inference_util.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6354944&bid=20632947)

**Comment by ilogue** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pyrsa/util/pooling.py  18
- pyrsa/model/fitter.py  5
         

Complexity decreasing per file
==============================
+ pyrsa/util/inference_util.py  -5
         

Clones added
============
- pyrsa/util/pooling.py  2
         

Clones removed
==============
+ pyrsa/util/inference_util.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6354944&bid=20632947)

**Comment by ilogue** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pyrsa/util/pooling.py  18
- pyrsa/model/fitter.py  5
         

Complexity decreasing per file
==============================
+ pyrsa/util/inference_util.py  -5
         

Clones added
============
- pyrsa/util/pooling.py  2
         

Clones removed
==============
+ pyrsa/util/inference_util.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6354944&bid=20632947)

**Comment by JasperVanDenBosch** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 1
           

Complexity increasing per file
==============================
- pyrsa/util/pooling.py  18
- pyrsa/model/fitter.py  5
         

Complexity decreasing per file
==============================
+ pyrsa/util/inference_util.py  -5
         

Clones added
============
- pyrsa/util/pooling.py  2
- tests/test_util_rdm.py  2
         

Clones removed
==============
+ pyrsa/util/inference_util.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6354944&bid=20632947)

**Comment by HeikoSchuett** [comment]
This took a bit more changes than expected.
Besides the update to include a linear algebra fitter, which is indeed considerably faster (up to 10x) this also contains a few additional tests, a bug fix in the pooling for Jörns new metrics and some passing through for sigma_k which is needed for computing Jörns dissimilarities.

**Comment by HeikoSchuett** [comment]
I have now run into the issue that the covariance weighted distances are not working for nans in the vectors. Will code this as a new pull request first

**Pull request merged**
