### PR TITLE
t-test based model comparisons

### PR DESCRIPTION
**Pull request by HeikoSchuett**
This pull request implements t-tests for the model comparisons.

To enable this I implemented saving the relevant noise covariances in the result object. This also allows the fancy evaluation I am currently evaluating, which results only in a variance estimate not in bootstrap samples.

This also has a connection to the model-plot function to display t-test based results

### CODE REVIEW

**Comment by HeikoSchuett** [comment]
This component should now be ready to be taken into master

**Comment by ilogue** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
           

Complexity increasing per file
==============================
- pyrsa/inference/crossvalsets.py  2
- pyrsa/vis/model_plot.py  10
         

Complexity decreasing per file
==============================
+ pyrsa/inference/evaluate.py  -2
         

Clones added
============
- pyrsa/inference/evaluate.py  1
- pyrsa/util/inference_util.py  2
         

Clones removed
==============
+ tests/test_crossval.py  -5
+ tests/test_inference.py  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6203568&bid=20232825)

**Comment by JasperVanDenBosch** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
           

Complexity increasing per file
==============================
- pyrsa/vis/model_plot.py  10
- pyrsa/inference/crossvalsets.py  2
         

Complexity decreasing per file
==============================
+ pyrsa/inference/evaluate.py  -2
         

Clones added
============
- pyrsa/inference/evaluate.py  1
- pyrsa/util/inference_util.py  2
         

Clones removed
==============
+ tests/test_inference.py  -6
+ tests/test_crossval.py  -5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6203568&bid=20232825)

**Comment by HeikoSchuett** [comment]
Closing this pull request. The content is now part of #145

**Pull request closed without merging**
