### PR TITLE
inference module development: bootstrap

### PR DESCRIPTION
**Pull request by HeikoSchuett**
This shall be the place to develop the bootstrapping part of inference

### CODE REVIEW

**Review by jdiedrichsen — APPROVED** [review]

**Review by iancharest — COMMENTED** [review]
Should we implement the bootstrap sampling before merging into master?

**Comment by HeikoSchuett** [comment]
Definitely, this is sill in development. Here I was waiting for the other branches to be committed

**Comment by HeikoSchuett** [comment]
Ok, now this generates single bootstrap samples. Next step is generating may + evaluating models on them

**Comment by HeikoSchuett** [comment]
OK guys, I think we should merge this into master! We will probably implement some more stuff in the future, but these bootstraps and cross validations seem to work for now and will be necessary elsewhere!

**Comment by JasperVanDenBosch** [comment]
I can review by feb 29

**Comment by HeikoSchuett** [comment]
> I can review by feb 29

That would be fantastic. Should not stop anyone else from having a look.

**Review by iancharest — APPROVED** [review]
This looks good to me.

**Pull request merged**
