### PR TITLE
Demos

### LINKED ISSUE #55: Corrections for multiple testing for pairwise tests
We should get the corrections for multiple testing implemented. So far there are none.

### PR DESCRIPTION
**Pull request by HeikoSchuett**
requires #51 
Also some plotting tools are missing to do some of the demo actions

### CODE REVIEW

**Review by iancharest — COMMENTED** [review]
I've tried the jupyter notebook demo, and I am missing the ('rdms_inferring/modelRDMs.mat') on the branch. is it meant to be in the demos folder?

**Comment by HeikoSchuett** [comment]
> I've tried the jupyter notebook demo, and I am missing the ('rdms_inferring/modelRDMs.mat') on the branch. is it meant to be in the demos folder?

Especially the noisy RDMs are quite large (30 MB). Thus I did not want to put them into Github. I could send you the files in another way. For the final version for the toolbox my plan was to reduce the file size by providing fewer possible simulated data.

**Review by iancharest — APPROVED** [review]
Looks all good to me!

**Review by doerlbh — APPROVED** [review]
looks good to me.

**Pull request merged**
