### PR TITLE
corr dist using einsum and test case using np.corrcoef

### PR DESCRIPTION
**Pull request by iancharest**
Hi all,
I've implemented corr dist using einsum for symmetry with the other distance metrics. 
on my machine it passes the tests. but i am relatively new to einsum so a second opinion would be appreciated.

### CODE REVIEW

**Review by HeikoSchuett — APPROVED** [review]
Looks fine to me! Sorry for the wait. I was away last week. 

Did you check whether it is actually faster this way?

**Comment by HeikoSchuett** [comment]
closes #39

**Review by eberlot — APPROVED** [review]
This implementation also looks fine to me.

**Review by doerlbh — APPROVED** [review]
Looks good to me. Thanks!

**Pull request merged**
