### PR TITLE
Initial simulation code

### PR DESCRIPTION
**Pull request by jdiedrichsen**
make_design: Make a simple fMRI design
make_dataset: Make a data set from an RDM model

Code is not ready yet - waiting for figure out the import pyrsa question that I posted on slack

### CODE REVIEW

**Review by HeikoSchuett — APPROVED** [review]
Any comments after my fix?

**Comment by JasperVanDenBosch** [comment]
> Any comments after my fix?

Sorry I just don't understand what's going on here well enough to comment on it I'm afraid. Like `vector of parameters`.. to describe the HRF? Spatial patterns?

**Comment by HeikoSchuett** [comment]
I think we can put this into master for now. We might want to add some more simulation data, but this seems fine to me for what is supposed to do.

**Comment by ilogue** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- tests/test_simulation.py  1
- pyrsa/simulation/sim.py  14
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6203571&bid=20232828)

**Comment by ilogue** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/test_simulation.py  1
- pyrsa/simulation/sim.py  14
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6203571&bid=20232828)

**Review by JasperVanDenBosch — CHANGES_REQUESTED** [review]
I've made some style fixes and otherwise it looks good. I have two questions:

1. What is a "Partition" (in the context of an fMRI design) and is `part_vec` required? It is not referred to in the other functions or in the tests.
2. Why does it throw a `NameError` for the dimensions? Should this be a `ValueError`?

**Comment by ilogue** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/test_simulation.py  1
- pyrsa/simulation/sim.py  14
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6203571&bid=20232828)

**Comment by JasperVanDenBosch** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/test_simulation.py  1
- pyrsa/simulation/sim.py  14
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6203571&bid=20232828)

**Comment by HeikoSchuett** [comment]
> I've made some style fixes and otherwise it looks good. I have two questions:
> 
> 1. What is a "Partition" (in the context of an fMRI design) and is `part_vec` required? It is not referred to in the other functions or in the tests.
> 2. Why does it throw a `NameError` for the dimensions? Should this be a `ValueError`?

The second one was easy I just replaced that. I am pretty sure that ValueError is better.

For the first: I think this encodes the run or repetition of the measurement. That is probably good to have for things like cross-validated distances. So, I would keep this although it is not used much now.

**Review by JasperVanDenBosch — APPROVED** [review]
Sounds good

**Pull request merged**
