### PR TITLE
Poisson distribution based calculation of RDMs

### PR DESCRIPTION
**Pull request by HeikoSchuett**
This pull request implements the symmetrized KL-divergence based RDM calculation for spiking data.

### CODE REVIEW

**Review by doerlbh — APPROVED** [review]
looks good to me!

**Comment by JasperVanDenBosch** [comment]
@HeikoSchuett This has the `sort` branch in it, so we'll wait with this one until that one is merged?

**Comment by HeikoSchuett** [comment]
I am also happy to merge this one and delete the sort branch. I just made the sort branch pull request for Alex to find the sort branch.

**Comment by JasperVanDenBosch** [comment]
Okay got it!

**Comment by JasperVanDenBosch** [comment]
The crossvalidated poisson currently leads to negative dissimilarities, is this intended?

**Comment by HeikoSchuett** [comment]
This is the same issue as for the cross validated Mahalanobis or euclidean distances. If there is a true distance this should happen rarely, but it can happen if the difference in training and test set has opposite signs.

**Review by JasperVanDenBosch — APPROVED** [review]
I've added a test for the poisson one, fixed some minor style issues. Looks ok to me

**Pull request merged**
