### PR TITLE
Fix noise test with one additional requirement

### PR DESCRIPTION
**Pull request by doerlbh**
This PR fixed the following error by including parameterized as a requirement.

==================================== ERRORS ====================================
_________________ ERROR collecting tests/test_noise_ceiling.py _________________
ImportError while importing test module '/Users/DoerLBH/Dropbox (Personal)/Git/pyrsa/tests/test_noise_ceiling.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_noise_ceiling.py:11: in <module>
    from parameterized import parameterized
E   ModuleNotFoundError: No module named 'parameterized'

### CODE REVIEW

**Comment by doerlbh** [comment]
Let's wait until PR https://github.com/rsagroup/pyrsa/pull/102 is merged, so as to not duplicate our efforts.

**Comment by doerlbh** [comment]
> Let's wait until PR #102 is merged, so as to not duplicate our efforts.

BTW, PR #102 was merged a few hours ago. This current PR is now up to date with master, and ready to be reviewed.

**Review by HeikoSchuett — APPROVED** [review]

**Review by JasperVanDenBosch — CHANGES_REQUESTED** [review]
In principle this should be covered by https://github.com/rsagroup/pyrsa/blob/master/setup.py#L36 right? I think this could probably go in a serparate `test_requirements.txt` file or `tests/requirements.txt` as we do with docs. If we do put it in the main reqs file than we'd also have to get rid of https://github.com/rsagroup/pyrsa/blob/master/setup.py#L36.

**Comment by doerlbh** [comment]
> If we do put it in the main reqs file than we'd also have to get rid of https://github.com/rsagroup/pyrsa/blob/master/setup.py#L36.

Done! I have followed the same convention as the pyrsa/requirements.txt and docs/requirements.txt, to also placed a tests/requirements.txt in the test folder. As a result, I also fixed the setup.py to reflect that.

**Review by JasperVanDenBosch — APPROVED** [review]

**Pull request merged**
