### PR TITLE
Vis rdm comparison scatterplot

### LINKED ISSUE #105: Scatterplot of RDM dissimilarities

### PR DESCRIPTION
**Pull request by caiw**

### CODE REVIEW

**Comment by caiw** [comment]
Pausing for tonight.  I'm only going to be around for a few hours tomorrow, so I'll join call if I can.  Otherwise I'll finish up the pull request over the next few days and request a review.

**Comment by HeikoSchuett** [comment]
Hi! How drafty is this one? Could/should we have a look already? Or are you planning to work more on this soon?

**Comment by caiw** [comment]
It's not ready for review yet. I have a big submission deadline at the end of this week; after that I plan to get this PR to a reviewable state.

**Comment by caiw** [comment]
I'm switching this to "ready to review" to get some feedback on exactly what is needed to make it "merge-worthy".  I have a function, some rudimentary tests (it's a visualisation function, but I added some other library code, and accompanying tests), and a working example script. I'd ideally like someone to work with me to discuss what's needed to merge it, but kicking it back with basic comments would also be fine.

**Comment by caiw** [comment]
Also, I realise it's not passing all checks, but I don't understand all of them.

**Comment by HeikoSchuett** [comment]
Hi @caiw, great that you found some time to continue on this plot! I would be happy to sit down with you for a short meeting to fix remaining issues, but overall this already looks quite good. Can you write me an email for scheduling?

In the meantime it would be great if you could fix the automatically raised flags:

- Skimming through the reports it looks like Travis CI (which just runs the provided tests) raises primarily a backwards compatibility problem: You use `from math import comb` which only exists since python 3.9. Replacing this with `from scipy.special import comb` should make all the tests pass again I think. 

- On the complaints from CodeFactor we can be a bit less strict, but it would also be great if you just click on Details behind its check and adjust the code to keep the style a bit more consistent with the rest. Don't worry about the complexity issues, but it would be great if you could fix the complaints about too long lines and import order.

**Comment by caiw** [comment]
> Hi @caiw, great that you found some time to continue on this plot! I would be happy to sit down with you for a short meeting to fix remaining issues, but overall this already looks quite good. Can you write me an email for scheduling?

Sure, I'll drop you an email!  Thanks!

> 
> In the meantime it would be great if you could fix the automatically raised flags:
> 
> * Skimming through the reports it looks like Travis CI (which just runs the provided tests) raises primarily a backwards compatibility problem: You use `from math import comb` which only exists since python 3.9. Replacing this with `from scipy.special import comb` should make all the tests pass again I think.

Ah yes, good point. I've fixed that.

> * On the complaints from CodeFactor we can be a bit less strict, but it would also be great if you just click on Details behind its check and adjust the code to keep the style a bit more consistent with the rest. Don't worry about the complexity issues, but it would be great if you could fix the complaints about too long lines and import order.

The import order thing is due to my inclusion of local imports inside a `if __name__ == "__main__":` block, used for testing and an example run. I will remove this before the final merge, but it may be useful when reviewing it.

Line length I can do.  Looks like my IDE's column guide was at 120 chars and I had been keeping to that. Silly me!

**Comment by HeikoSchuett** [comment]
Hi @caiw , I would like to clean up the pull requests a bit. As this was already near finished: Do you maybe have time to finish this soon?

**Comment by caiw** [comment]
@HeikoSchuett, I'm currently preparing to go on an extended period of leave (several months) which is taking up rather a lot of my time.  Nevertheless I will see if I can make some progress on this, at least bringing it up to date with `main`, addressing the style issues already highlighted, and getting checks to pass. I'll reply anon.

**Comment by caiw** [comment]
@HeikoSchuett I have brought this up to date with `main`, and all tests pass except four CodeFactor tests. The first three of these relate to a `if __name__ == "__main__":` block which might help code review, but which will be removed before merging. The fourth is complaining about relative importing, but I don't understand it: it seems fine to me.

To return to my [above comment](https://github.com/rsagroup/rsatoolbox/pull/106#issuecomment-765567219), the PR could use some reviewer attention to decide what it needs to be mergeable. Given my above-mentioned time constraints I would prefer to do this asynchronously (even if it takes longer), but could meet if necessary.

**Comment by HeikoSchuett** [comment]
Hi Cai, I think this is done now. I just converted the code snippet you had in the __main__ part into a demo and a test and it is now all working.
If you have time at some point, you could invest it in some more beautiful defaults, like making sure that the histograms and the axis titles do not overlap etc., but feel free to use a new pull request if you want to do this.

**Comment by caiw** [comment]
Perfect, thank you. I'll prettify it when I can, but I must admit it'll quite far on the back burner for at least the net 6 months.

**Pull request merged**
