### PR TITLE
Inference improvements: t-tests, bootstrap-cv, rank-tests

### PR DESCRIPTION
**Pull request by HeikoSchuett**
This pull request contains the current updates to the inference engine.
Specifically it implements the corrections for the bootstrap wrapped cross-validation and the t-test and rank-sum tests.

I had these in separate pull requests originally, but they really depend on each other such later additions would contain the earlier pull requests.  

Merging this branch would be a gigantic improvement to the inference machine!

### CODE REVIEW

**Comment by ilogue** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 8
           

Complexity increasing per file
==============================
- pyrsa/inference/crossvalsets.py  2
- pyrsa/inference/evaluate.py  3
- pyrsa/vis/model_plot.py  10
         

Clones added
============
- pyrsa/inference/evaluate.py  1
- pyrsa/util/inference_util.py  2
         

Clones removed
==============
+ tests/test_crossval.py  -5
+ tests/test_inference.py  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6314804&bid=20531390)

**Comment by ilogue** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 8
           

Complexity increasing per file
==============================
- pyrsa/inference/evaluate.py  3
- pyrsa/inference/crossvalsets.py  2
- pyrsa/vis/model_plot.py  4
         

Clones added
============
- pyrsa/inference/evaluate.py  1
- pyrsa/util/inference_util.py  2
         

Clones removed
==============
+ tests/test_inference.py  -6
+ tests/test_crossval.py  -5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6314804&bid=20531390)

**Comment by ilogue** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 8
           

Complexity increasing per file
==============================
- pyrsa/inference/crossvalsets.py  2
- pyrsa/vis/model_plot.py  4
- pyrsa/inference/evaluate.py  3
         

Clones added
============
- pyrsa/util/inference_util.py  2
- pyrsa/inference/evaluate.py  1
         

Clones removed
==============
+ tests/test_crossval.py  -5
+ tests/test_inference.py  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6314804&bid=20531390)

**Comment by ilogue** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 8
           

Complexity increasing per file
==============================
- pyrsa/inference/crossvalsets.py  2
- pyrsa/inference/evaluate.py  3
         

Complexity decreasing per file
==============================
+ pyrsa/vis/model_plot.py  -16
         

Clones added
============
- pyrsa/vis/model_plot.py  2
- pyrsa/util/inference_util.py  2
- pyrsa/inference/evaluate.py  1
         

Clones removed
==============
+ tests/test_crossval.py  -5
+ tests/test_inference.py  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6314804&bid=20531390)

**Comment by ilogue** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 8
           

Complexity increasing per file
==============================
- pyrsa/inference/evaluate.py  3
- pyrsa/inference/crossvalsets.py  2
         

Complexity decreasing per file
==============================
+ pyrsa/vis/model_plot.py  -16
         

Clones added
============
- pyrsa/inference/evaluate.py  1
- pyrsa/vis/model_plot.py  2
- pyrsa/util/inference_util.py  2
         

Clones removed
==============
+ tests/test_inference.py  -6
+ tests/test_crossval.py  -5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6314804&bid=20531390)

**Comment by ilogue** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 8
- Added 2
           

Complexity increasing per file
==============================
- pyrsa/inference/evaluate.py  3
- pyrsa/inference/crossvalsets.py  2
- tests/test_vis.py  1
         

Complexity decreasing per file
==============================
+ pyrsa/vis/model_plot.py  -16
         

Clones added
============
- pyrsa/inference/evaluate.py  1
- pyrsa/vis/model_plot.py  2
- pyrsa/util/inference_util.py  2
         

Clones removed
==============
+ tests/test_crossval.py  -5
+ tests/test_inference.py  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6314804&bid=20531390)

**Comment by ilogue** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 8
- Added 2
           

Complexity increasing per file
==============================
- pyrsa/inference/evaluate.py  3
- pyrsa/inference/crossvalsets.py  2
         

Complexity decreasing per file
==============================
+ pyrsa/vis/model_plot.py  -16
         

Clones added
============
- pyrsa/vis/model_plot.py  2
- pyrsa/util/inference_util.py  2
- pyrsa/inference/evaluate.py  1
         

Clones removed
==============
+ tests/test_inference.py  -6
+ tests/test_crossval.py  -5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6314804&bid=20531390)

**Comment by JasperVanDenBosch** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 8
           

Complexity increasing per file
==============================
- pyrsa/inference/evaluate.py  3
- pyrsa/inference/crossvalsets.py  2
         

Complexity decreasing per file
==============================
+ pyrsa/vis/model_plot.py  -13
         

Clones added
============
- pyrsa/inference/evaluate.py  1
- pyrsa/vis/model_plot.py  2
- pyrsa/util/inference_util.py  2
         

Clones removed
==============
+ tests/test_inference.py  -6
+ tests/test_crossval.py  -5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6314804&bid=20531390)

**Pull request merged**
