### PR TITLE
searchlight

### PR DESCRIPTION
**Pull request by lajnd**
Implementing the searchlight

### CODE REVIEW

**Review by JasperVanDenBosch — CHANGES_REQUESTED** [review]
This generally looks good to me and useful. Sorry if this has come up before and I missed it,
but did you consider just putting all the spheres in one `DataSet`? And then move the chunking to inside `calc_rdm`? This might not be the only situation where we have a large dataset from which we want to calculate many RDMs. Just a thought.

And could you have a look with `pylint pyrsa/util/searchlight.py`? It's mostly the white space. Codacy should be doing this but for some reason the integration is not working the last few days..

**Comment by ilogue** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 9
           

Complexity increasing per file
==============================
- tests/test_searchlight.py  3
- pyrsa/util/searchlight.py  6
         

Clones added
============
- pyrsa/util/searchlight.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6203560&bid=20232817)

**Comment by ilogue** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- tests/test_searchlight.py  3
- pyrsa/util/searchlight.py  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6203560&bid=20232817)

**Comment by ilogue** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- tests/test_searchlight.py  3
- pyrsa/util/searchlight.py  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6203560&bid=20232817)

**Comment by JasperVanDenBosch** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/test_searchlight.py  3
- pyrsa/util/searchlight.py  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/rsagroup/pyrsa/pullRequest?prid=6203560&bid=20232817)

**Review by JasperVanDenBosch — APPROVED** [review]
Thanks for the style fixes

**Review by iancharest — APPROVED** [review]
This is good to go now. would be good in the future to add some more example with alternative metrics in the notebook.

**Pull request merged**
